/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpAlert {
        "alertTitle": string;
        "message": string;
        "type": 'info' | 'warning' | 'danger' | 'success';
    }
}
declare global {
    interface HTMLIpAlertElement extends Components.IpAlert, HTMLStencilElement {
    }
    var HTMLIpAlertElement: {
        prototype: HTMLIpAlertElement;
        new (): HTMLIpAlertElement;
    };
    interface HTMLElementTagNameMap {
        "ip-alert": HTMLIpAlertElement;
    }
}
declare namespace LocalJSX {
    interface IpAlert {
        "alertTitle"?: string;
        "message"?: string;
        "type"?: 'info' | 'warning' | 'danger' | 'success';
    }
    interface IntrinsicElements {
        "ip-alert": IpAlert;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-alert": LocalJSX.IpAlert & JSXBase.HTMLAttributes<HTMLIpAlertElement>;
        }
    }
}
