/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpDropdown {
        "dropTitle": string;
        "options": string[];
    }
}
declare global {
    interface HTMLIpDropdownElement extends Components.IpDropdown, HTMLStencilElement {
    }
    var HTMLIpDropdownElement: {
        prototype: HTMLIpDropdownElement;
        new (): HTMLIpDropdownElement;
    };
    interface HTMLElementTagNameMap {
        "ip-dropdown": HTMLIpDropdownElement;
    }
}
declare namespace LocalJSX {
    interface IpDropdown {
        "dropTitle"?: string;
        "options"?: string[];
    }
    interface IntrinsicElements {
        "ip-dropdown": IpDropdown;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-dropdown": LocalJSX.IpDropdown & JSXBase.HTMLAttributes<HTMLIpDropdownElement>;
        }
    }
}
