/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpDropFile {
        "accept": string;
        "downloadLabel": string;
        "fileSize": string;
        "maxFileSize": number;
        "pauseLabel": string;
        "placeholder": string;
        "removeFileLabel": string;
        "resumeLabel": string;
        "timeLeft": string;
    }
}
export interface IpDropFileCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIpDropFileElement;
}
declare global {
    interface HTMLIpDropFileElementEventMap {
        "fileUploaded": File;
    }
    interface HTMLIpDropFileElement extends Components.IpDropFile, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIpDropFileElementEventMap>(type: K, listener: (this: HTMLIpDropFileElement, ev: IpDropFileCustomEvent<HTMLIpDropFileElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIpDropFileElementEventMap>(type: K, listener: (this: HTMLIpDropFileElement, ev: IpDropFileCustomEvent<HTMLIpDropFileElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIpDropFileElement: {
        prototype: HTMLIpDropFileElement;
        new (): HTMLIpDropFileElement;
    };
    interface HTMLElementTagNameMap {
        "ip-drop-file": HTMLIpDropFileElement;
    }
}
declare namespace LocalJSX {
    interface IpDropFile {
        "accept"?: string;
        "downloadLabel"?: string;
        "fileSize"?: string;
        "maxFileSize"?: number;
        "onFileUploaded"?: (event: IpDropFileCustomEvent<File>) => void;
        "pauseLabel"?: string;
        "placeholder"?: string;
        "removeFileLabel"?: string;
        "resumeLabel"?: string;
        "timeLeft"?: string;
    }
    interface IntrinsicElements {
        "ip-drop-file": IpDropFile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-drop-file": LocalJSX.IpDropFile & JSXBase.HTMLAttributes<HTMLIpDropFileElement>;
        }
    }
}
