/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpDropFile {
        "accept": string;
        "downloadLabel": string;
        "fileSize": string;
        "maxFileSize": number;
        "pauseLabel": string;
        "placeholder": string;
        "removeFileLabel": string;
        "resumeLabel": string;
        "timeLeft": string;
    }
}
declare global {
    interface HTMLIpDropFileElement extends Components.IpDropFile, HTMLStencilElement {
    }
    var HTMLIpDropFileElement: {
        prototype: HTMLIpDropFileElement;
        new (): HTMLIpDropFileElement;
    };
    interface HTMLElementTagNameMap {
        "ip-drop-file": HTMLIpDropFileElement;
    }
}
declare namespace LocalJSX {
    interface IpDropFile {
        "accept"?: string;
        "downloadLabel"?: string;
        "fileSize"?: string;
        "maxFileSize"?: number;
        "pauseLabel"?: string;
        "placeholder"?: string;
        "removeFileLabel"?: string;
        "resumeLabel"?: string;
        "timeLeft"?: string;
    }
    interface IntrinsicElements {
        "ip-drop-file": IpDropFile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-drop-file": LocalJSX.IpDropFile & JSXBase.HTMLAttributes<HTMLIpDropFileElement>;
        }
    }
}
