/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpTooltip {
        "btn1AriaLabel": string;
        "btn2AriaLabel": string;
        "hoverTooltip": boolean;
        "tooltipBtn1": string;
        "tooltipBtn2": string;
        "tooltipBtnClose": boolean;
        "tooltipContent": string;
        "tooltipTitle": string;
        "tooltipTrigger": string;
    }
}
declare global {
    interface HTMLIpTooltipElement extends Components.IpTooltip, HTMLStencilElement {
    }
    var HTMLIpTooltipElement: {
        prototype: HTMLIpTooltipElement;
        new (): HTMLIpTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "ip-tooltip": HTMLIpTooltipElement;
    }
}
declare namespace LocalJSX {
    interface IpTooltip {
        "btn1AriaLabel"?: string;
        "btn2AriaLabel"?: string;
        "hoverTooltip"?: boolean;
        "tooltipBtn1"?: string;
        "tooltipBtn2"?: string;
        "tooltipBtnClose"?: boolean;
        "tooltipContent"?: string;
        "tooltipTitle"?: string;
        "tooltipTrigger"?: string;
    }
    interface IntrinsicElements {
        "ip-tooltip": IpTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-tooltip": LocalJSX.IpTooltip & JSXBase.HTMLAttributes<HTMLIpTooltipElement>;
        }
    }
}
