/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpEmail {
        "emptyFieldErrorMessage": string;
        "errorMessage": string;
        "inputLabel": string;
        "inputPlaceholder": string;
        "invalid": boolean;
        "required": boolean;
    }
    interface IpLogin {
        "forgotPasswordLabel": string;
        "forgotPasswordLink": string;
        "hidePasswordAriaLabel": string;
        "indicationLabel": string;
        "loginTitle": string;
        "passwordDigitErrorMsg": string;
        "passwordLabel": string;
        "passwordLengthErrorMsg": string;
        "passwordLowercaseErrorMsg": string;
        "passwordUppercaseErrorMsg": string;
        "pwdPlaceholder": string;
        "showPasswordAriaLabel": string;
        "submitBtnAriaLabel": string;
        "submitButtonLabel": string;
        "usernameErrorMsg": string;
        "usernameInvalidEmailMsg": string;
        "usernameLabel": string;
        "usernamePlaceholder": string;
        "usernameRequired": boolean;
        "usernameType": 'text' | 'email';
    }
    interface IpPassword {
        "emptyFieldErrorMessage": string;
        "errorMessage": string;
        "forgotPasswordLink": string;
        "hidePasswordAriaLabel": string;
        "inputPlaceholder": string;
        "invalid": boolean;
        "showPasswordAriaLabel": string;
    }
}
export interface IpEmailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIpEmailElement;
}
export interface IpLoginCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIpLoginElement;
}
export interface IpPasswordCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIpPasswordElement;
}
declare global {
    interface HTMLIpEmailElementEventMap {
        "inputChange": string;
    }
    interface HTMLIpEmailElement extends Components.IpEmail, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIpEmailElementEventMap>(type: K, listener: (this: HTMLIpEmailElement, ev: IpEmailCustomEvent<HTMLIpEmailElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIpEmailElementEventMap>(type: K, listener: (this: HTMLIpEmailElement, ev: IpEmailCustomEvent<HTMLIpEmailElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIpEmailElement: {
        prototype: HTMLIpEmailElement;
        new (): HTMLIpEmailElement;
    };
    interface HTMLIpLoginElementEventMap {
        "formSubmitted": any;
    }
    interface HTMLIpLoginElement extends Components.IpLogin, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIpLoginElementEventMap>(type: K, listener: (this: HTMLIpLoginElement, ev: IpLoginCustomEvent<HTMLIpLoginElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIpLoginElementEventMap>(type: K, listener: (this: HTMLIpLoginElement, ev: IpLoginCustomEvent<HTMLIpLoginElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIpLoginElement: {
        prototype: HTMLIpLoginElement;
        new (): HTMLIpLoginElement;
    };
    interface HTMLIpPasswordElementEventMap {
        "passwordChange": string;
    }
    interface HTMLIpPasswordElement extends Components.IpPassword, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIpPasswordElementEventMap>(type: K, listener: (this: HTMLIpPasswordElement, ev: IpPasswordCustomEvent<HTMLIpPasswordElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIpPasswordElementEventMap>(type: K, listener: (this: HTMLIpPasswordElement, ev: IpPasswordCustomEvent<HTMLIpPasswordElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIpPasswordElement: {
        prototype: HTMLIpPasswordElement;
        new (): HTMLIpPasswordElement;
    };
    interface HTMLElementTagNameMap {
        "ip-email": HTMLIpEmailElement;
        "ip-login": HTMLIpLoginElement;
        "ip-password": HTMLIpPasswordElement;
    }
}
declare namespace LocalJSX {
    interface IpEmail {
        "emptyFieldErrorMessage"?: string;
        "errorMessage"?: string;
        "inputLabel"?: string;
        "inputPlaceholder"?: string;
        "invalid"?: boolean;
        "onInputChange"?: (event: IpEmailCustomEvent<string>) => void;
        "required"?: boolean;
    }
    interface IpLogin {
        "forgotPasswordLabel"?: string;
        "forgotPasswordLink"?: string;
        "hidePasswordAriaLabel"?: string;
        "indicationLabel"?: string;
        "loginTitle"?: string;
        "onFormSubmitted"?: (event: IpLoginCustomEvent<any>) => void;
        "passwordDigitErrorMsg"?: string;
        "passwordLabel"?: string;
        "passwordLengthErrorMsg"?: string;
        "passwordLowercaseErrorMsg"?: string;
        "passwordUppercaseErrorMsg"?: string;
        "pwdPlaceholder"?: string;
        "showPasswordAriaLabel"?: string;
        "submitBtnAriaLabel"?: string;
        "submitButtonLabel"?: string;
        "usernameErrorMsg"?: string;
        "usernameInvalidEmailMsg"?: string;
        "usernameLabel"?: string;
        "usernamePlaceholder"?: string;
        "usernameRequired"?: boolean;
        "usernameType"?: 'text' | 'email';
    }
    interface IpPassword {
        "emptyFieldErrorMessage"?: string;
        "errorMessage"?: string;
        "forgotPasswordLink"?: string;
        "hidePasswordAriaLabel"?: string;
        "inputPlaceholder"?: string;
        "invalid"?: boolean;
        "onPasswordChange"?: (event: IpPasswordCustomEvent<string>) => void;
        "showPasswordAriaLabel"?: string;
    }
    interface IntrinsicElements {
        "ip-email": IpEmail;
        "ip-login": IpLogin;
        "ip-password": IpPassword;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-email": LocalJSX.IpEmail & JSXBase.HTMLAttributes<HTMLIpEmailElement>;
            "ip-login": LocalJSX.IpLogin & JSXBase.HTMLAttributes<HTMLIpLoginElement>;
            "ip-password": LocalJSX.IpPassword & JSXBase.HTMLAttributes<HTMLIpPasswordElement>;
        }
    }
}
