/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuItem } from "./components/menu-1/menu1";
export { MenuItem } from "./components/menu-1/menu1";
export namespace Components {
    interface CustomMenu {
        "items": MenuItem[];
        "menuData": string;
    }
}
declare global {
    interface HTMLCustomMenuElement extends Components.CustomMenu, HTMLStencilElement {
    }
    var HTMLCustomMenuElement: {
        prototype: HTMLCustomMenuElement;
        new (): HTMLCustomMenuElement;
    };
    interface HTMLElementTagNameMap {
        "custom-menu": HTMLCustomMenuElement;
    }
}
declare namespace LocalJSX {
    interface CustomMenu {
        "items"?: MenuItem[];
        "menuData"?: string;
    }
    interface IntrinsicElements {
        "custom-menu": CustomMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-menu": LocalJSX.CustomMenu & JSXBase.HTMLAttributes<HTMLCustomMenuElement>;
        }
    }
}
