/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuItem } from "./components/menu-1/burger-menu";
export { MenuItem } from "./components/menu-1/burger-menu";
export namespace Components {
    interface IpBurgerMenu {
        "closeMenuAriaLabel": string;
        "items": MenuItem[];
        "menuData": string;
        "openMenuAriaLabel": string;
        "pathToArrowRightIcon": string;
        "pathToCloseIcon": string;
        "pathToOpenIcon": string;
    }
}
declare global {
    interface HTMLIpBurgerMenuElement extends Components.IpBurgerMenu, HTMLStencilElement {
    }
    var HTMLIpBurgerMenuElement: {
        prototype: HTMLIpBurgerMenuElement;
        new (): HTMLIpBurgerMenuElement;
    };
    interface HTMLElementTagNameMap {
        "ip-burger-menu": HTMLIpBurgerMenuElement;
    }
}
declare namespace LocalJSX {
    interface IpBurgerMenu {
        "closeMenuAriaLabel"?: string;
        "items"?: MenuItem[];
        "menuData"?: string;
        "openMenuAriaLabel"?: string;
        "pathToArrowRightIcon"?: string;
        "pathToCloseIcon"?: string;
        "pathToOpenIcon"?: string;
    }
    interface IntrinsicElements {
        "ip-burger-menu": IpBurgerMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-burger-menu": LocalJSX.IpBurgerMenu & JSXBase.HTMLAttributes<HTMLIpBurgerMenuElement>;
        }
    }
}
