/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpTabPanel {
        "selectedTab": string;
        "tabPanelHeaders": TabPanelInterface[] | string;
        "tabPanelTitle": string;
        "titleTag": string;
    }
}
declare global {
    interface HTMLIpTabPanelElement extends Components.IpTabPanel, HTMLStencilElement {
    }
    var HTMLIpTabPanelElement: {
        prototype: HTMLIpTabPanelElement;
        new (): HTMLIpTabPanelElement;
    };
    interface HTMLElementTagNameMap {
        "ip-tab-panel": HTMLIpTabPanelElement;
    }
}
declare namespace LocalJSX {
    interface IpTabPanel {
        "selectedTab"?: string;
        "tabPanelHeaders"?: TabPanelInterface[] | string;
        "tabPanelTitle"?: string;
        "titleTag"?: string;
    }
    interface IntrinsicElements {
        "ip-tab-panel": IpTabPanel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-tab-panel": LocalJSX.IpTabPanel & JSXBase.HTMLAttributes<HTMLIpTabPanelElement>;
        }
    }
}
