/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpToggle {
        "activeLabel": string;
        "ariaLabel": string;
        "inactiveLabel": string;
        "size": "small" | "medium" | "large";
        "toggleDisabled": boolean;
    }
}
declare global {
    interface HTMLIpToggleElement extends Components.IpToggle, HTMLStencilElement {
    }
    var HTMLIpToggleElement: {
        prototype: HTMLIpToggleElement;
        new (): HTMLIpToggleElement;
    };
    interface HTMLElementTagNameMap {
        "ip-toggle": HTMLIpToggleElement;
    }
}
declare namespace LocalJSX {
    interface IpToggle {
        "activeLabel"?: string;
        "ariaLabel"?: string;
        "inactiveLabel"?: string;
        "size"?: "small" | "medium" | "large";
        "toggleDisabled"?: boolean;
    }
    interface IntrinsicElements {
        "ip-toggle": IpToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-toggle": LocalJSX.IpToggle & JSXBase.HTMLAttributes<HTMLIpToggleElement>;
        }
    }
}
