name: release

on:
  push:
    branches:
      - master
      - main
jobs:
  build-staging-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/pdfa11y
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}"
          file: ./apps/demo/docker/Dockerfile
          tags: |
            rg.fr-par.scw.cloud/pdfa11y/webcomponents-demo:latest

  deploy-on-staging:
    runs-on: ubuntu-latest
    needs: [build-staging-image]
    steps:
    - uses: passeidireto/trigger-external-workflow-action@main
      env:
        PAYLOAD_SERVICE: "webcomponents"
      with:
        repository: docaxess/pdfa11y-k8s-webservices
        event: deploy_staging
        github_pat: ${{ secrets.K8S_WEBSERVICES_PAT }}

    - uses: slackapi/slack-github-action@v1.26.0
      with:
        channel-id: 'C0779L6QQT1' #'saas-deployment'
        payload: |
          {
            "text": ":rocket: webcomponents.ipedis.com has been released on staging ! :tada: ( ${{ github.ref_name }} )"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.DEPLOYMENT_SLACK_BOT }}