name: Automatic Testing Flow
on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v5
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint all packages
        run: npm run lint

      - name: Build all packages
        run: npm run build

      - name: Test all packages
        run: npm run test

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Demo e2e tests
        run: npm run e2e

      - name: Demo Axe tests
        run: npm run e2e:axe

  axe-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dequelabs/axe-linter-action@v1
        with:
          api_key: ${{ secrets.AXE_LINTER_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
